In [ ]:
import sys
import os
sys.path.append(os.path.abspath(".."))
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from src.preprocessing import preprocessor, X, Y 
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC 
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import confusion_matrix 


# splitting input and output data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

# definition of a logistic regression model using a sequential processing chain (transforming pipeline)                               
chain = Pipeline(steps = [                       
    ("preprocessing", preprocessor),            
    ("pca", PCA()),                              
    ("linear_SVC", SVC())                       
] )

# parameters for GridSearchCV
param_grid = {
     'linear_SVC__C': [1, 10],
     'linear_SVC__max_iter': [1000, 5000],
     'linear_SVC__kernel': ['linear', 'rbf', 'poly', 'sigmoid'],
     'linear_SVC__gamma': ['auto', 'scale'], 
     'linear_SVC__class_weight': ['balanced'],
     'pca__n_components': [2,5]    
}

# definition of the GridSearchCV object 
grid_search = GridSearchCV(chain, param_grid, scoring='accuracy', cv = 5)

# training a SVM model
grid_search.fit(X_train, y_train)

# model prediction 
y_pred = grid_search.predict(X_test)

# evaluation of model fit using the accuracy metric
accuracy_values = accuracy_score (y_test, y_pred)

# evaluation of model fit using the precision metric
precision_values = precision_score (y_test, y_pred, average='macro')

# evaluation of model fit using the recall metric
recall_values = recall_score (y_test, y_pred, average = 'macro')

# evaluation of model fit using the confusion matrix 
confusionmatrix_values = confusion_matrix(y_test, y_pred, labels = ['low', 'middle', 'high'])




C:\Users\kejdi\anaconda3\envs\models\lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\kejdi\anaconda3\envs\models\lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\kejdi\anaconda3\envs\models\lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\kejdi\anaconda3\envs\models\lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expec

0.44594594594594594
0.4912828519385896
0.4155991831430428
[[26  0  1]
 [16  2  1]
 [19  4  5]]
              precision    recall  f1-score   support

        high      0.714     0.179     0.286        28
         low      0.426     0.963     0.591        27
      middle      0.333     0.105     0.160        19

    accuracy                          0.446        74
   macro avg      0.491     0.416     0.346        74
weighted avg      0.511     0.446     0.365        74

['low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'high' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'high' 'low' 'middle' 'low' 'low' 'low' 'low' 'middle' 'low' 'low'
 'middle' 'low' 'low' 'low' 'low' 'low' 'low' 'high' 'low' 'low' 'low'
 'low' 'high' 'low' 'low' 'low' 'middle' 'low' 'low' 'high' 'low' 'low'
 'high' 'low' 'low' 'high' 'middle' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'middle' 'low' 'low' 'low']
